# .github/workflows/deploy.yml

name: Deploy to Digital Ocean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    # This tells the job to use the 'Production' environment and its secrets.
    # It also enables protection rules, like only allowing the 'main' branch to deploy.
    environment: Production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Optional Build Step: Uncomment this if your site needs to be built.
      # - name: Build static files
      #   run: |
      #     npm install
      #     npm run build
      
      - name: Deploy files to server
        uses: appleboy/ssh-action@master
        with:
          # These secrets must be defined in your 'Production' environment settings
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}

          # 'source' is the directory in your repository you want to copy.
          # Use "./" for the entire repository.
          # If you have a build step, you might use "dist/" or "build/".
          source: "./"

          # 'target' is the destination path on your server.
          # This automatically uses your repository's name for the folder.
          target: "/var/www/${{ github.event.repository.name }}"